# Generated by Django 6.1.1 on 2026-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaFasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='fastas/')),
                ('nome_sequencia', models.CharField(blank=True, max_length=255)),
                ('sequencia', models.TextField(blank=True)),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('gc_percentual', models.FloatField(blank=True, null=True)),
                ('complemento_reverso', models.TextField(blank=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
    ]
